"""fix models

Revision ID: 9d07abe998ed
Revises: f52002e27982
Create Date: 2025-05-28 08:16:49.295792

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9d07abe998ed'
down_revision: Union[str, None] = 'f52002e27982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('turn', sa.Integer(), nullable=True))
    op.add_column('games', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('games', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('games', 'player1_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('games', 'board_player1',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('games', 'board_player2',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('games', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'games', 'users', ['turn'], ['id'])
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'created_at')
    op.drop_constraint(None, 'games', type_='foreignkey')
    op.alter_column('games', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('games', 'board_player2',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('games', 'board_player1',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('games', 'player1_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('games', 'updated_at')
    op.drop_column('games', 'created_at')
    op.drop_column('games', 'turn')
    # ### end Alembic commands ###
